version: '3.9'

services:
  db:
    images: postgres:16
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=blogdb
      - DB_USER=bloguser
      - DB_PASSWORD=blogpass
      - DB_HOST=db
    depends_on:
      - db

volumes:
  postgres_data: